/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Lokalitet;
import model.enumeracija.JedinicaGazdinstva;
import view.LokalitetiForma;

/**
 *
 * @author Andrej
 */
public class LokalitetDialog extends javax.swing.JDialog {

    private Lokalitet lokalitet;
    private LokalitetiForma parent;

    public LokalitetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Kreiraj lokalitet");
        inicijalizacija();
        this.parent = (LokalitetiForma) parent;
    }

    public LokalitetDialog(java.awt.Frame parent, boolean modal, Lokalitet lokalitet) {
        super(parent, modal);
        this.lokalitet = lokalitet;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Detalji lokaliteta");
        inicijalizacija(lokalitet);
        this.parent = (LokalitetiForma) parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldOdsekOdeljenje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDoznaka = new javax.swing.JTextField();
        jComboBoxJG = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDatumDoznake = new javax.swing.JTextField();
        jLabelJGError = new javax.swing.JLabel();
        jLabelOOError = new javax.swing.JLabel();
        jLabelDoznakaError = new javax.swing.JLabel();
        jLabelDatumDoznakeError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSacuvajIzmene = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();

        jButton3.setText("Izmeni");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Odsek i odeljenje");

        jTextFieldOdsekOdeljenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOdsekOdeljenjeActionPerformed(evt);
            }
        });

        jLabel2.setText("Gazdinska jedinica");

        jLabel3.setText("Doznaka");

        jComboBoxJG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJGActionPerformed(evt);
            }
        });

        jLabel4.setText("Datum doznake");

        jTextFieldDatumDoznake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumDoznakeActionPerformed(evt);
            }
        });

        jLabelJGError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelJGError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelJGError.setText("jLabel5");

        jLabelOOError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelOOError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelOOError.setText("jLabel5");

        jLabelDoznakaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelDoznakaError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDoznakaError.setText("jLabel5");

        jLabelDatumDoznakeError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelDatumDoznakeError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDatumDoznakeError.setText("jLabel5");

        jLabel6.setText("m3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDatumDoznake, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDoznakaError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatumDoznakeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldDoznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJGError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxJG, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOOError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldOdsekOdeljenje))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxJG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabelJGError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldOdsekOdeljenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabelOOError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDoznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDoznakaError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatumDoznake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDatumDoznakeError)
                .addGap(10, 10, 10))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSacuvajIzmene.setText("Sačuvaj izmene");
        jButtonSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajIzmeneActionPerformed(evt);
            }
        });

        jButtonIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonKreiraj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSacuvajIzmene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSacuvajIzmene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonKreiraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonObrisi)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        jTextFieldOdsekOdeljenje.setEnabled(true);
        jTextFieldDatumDoznake.setEnabled(false);
        jTextFieldDoznaka.setEnabled(false);
        jComboBoxJG.setEnabled(true);
        jButtonIzmeni.setEnabled(false);
        jButtonSacuvajIzmene.setEnabled(true);
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jComboBoxJGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJGActionPerformed

    private void jTextFieldOdsekOdeljenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOdsekOdeljenjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOdsekOdeljenjeActionPerformed

    private void jButtonSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajIzmeneActionPerformed
        this.setValidationLabels();
        if (jComboBoxJG.getSelectedItem() == null 
                || jTextFieldOdsekOdeljenje.getText().isEmpty() 
                || jTextFieldDoznaka.getText().isEmpty() 
                || !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?")
                || jTextFieldDatumDoznake.getText().isEmpty()) {
            jLabelJGError.setText(jComboBoxJG.getSelectedItem() == null ? "Unesite jedinicu gazdinstva" : "");
            jLabelOOError.setText(jTextFieldOdsekOdeljenje.getText().isEmpty() ? "Unesite odsek i odeljenje" : "");
            jLabelDoznakaError.setText(jTextFieldDoznaka.getText().isEmpty() ? "Unesite doznaku" : "");
            return;
        }

        JedinicaGazdinstva jg = (JedinicaGazdinstva) jComboBoxJG.getSelectedItem();
        String odsekOdeljenje = jTextFieldOdsekOdeljenje.getText();
        double doznaka = Double.parseDouble(jTextFieldDoznaka.getText());
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        java.util.Date datum = null;

        try {
            datum = format.parse(jTextFieldDatumDoznake.getText());
        } catch (ParseException ex) {
            Logger.getLogger(LokalitetDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.lokalitet.setJedinicaGazdinstva(jg);
        this.lokalitet.setOdsekOdeljenje(odsekOdeljenje);
        this.lokalitet.setDoznaka(doznaka);
        this.lokalitet.setDatumDoznake(datum);

        boolean uspesno = Controller.getInstance().izmeniLokalitet(lokalitet);
        if (!uspesno) {
            JOptionPane.showMessageDialog(this, "Greška prilikom izmene lokaliteta", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Uspešno izmenjen lokalitet", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSacuvajIzmeneActionPerformed

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        this.setValidationLabels();
        if (jComboBoxJG.getSelectedItem() == null || jTextFieldOdsekOdeljenje.getText().isEmpty() 
                || jTextFieldDoznaka.getText().isEmpty() 
                || !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?") 
                || jTextFieldDatumDoznake.getText().isEmpty()) {
            jLabelJGError.setText(jComboBoxJG.getSelectedItem() == null ? "Unesite jedinicu gazdinstva" : "");
            jLabelOOError.setText(jTextFieldOdsekOdeljenje.getText().isEmpty() ? "Unesite odsek i odeljenje" : "");
            jLabelDoznakaError.setText(jTextFieldDoznaka.getText().isEmpty() ? "Unesite doznaku"
                    : !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?") ? "Unesite broj" : "");
            return;
        }

        JedinicaGazdinstva jg = (JedinicaGazdinstva) jComboBoxJG.getSelectedItem();
        String oo = jTextFieldOdsekOdeljenje.getText();
        double doznaka = Double.parseDouble(jTextFieldDoznaka.getText());
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        java.util.Date datum;

        try {
            datum = format.parse(jTextFieldDatumDoznake.getText());
        } catch (ParseException ex) {
            Logger.getLogger(LokalitetDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Pogrešan format datuma", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Lokalitet lokalitet = new Lokalitet(0, jg, oo, doznaka, datum);
        boolean uspesno = Controller.getInstance().kreirajLokalitet(lokalitet);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Lokalitet uspešno kreiran", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            parent.azurirajTabelu();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja lokaliteta", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jTextFieldDatumDoznakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumDoznakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatumDoznakeActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete lokalitet?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION) {
            boolean uspesno = Controller.getInstance().obrisiLokalitet(lokalitet);
            if (!uspesno) {
                JOptionPane.showMessageDialog(this, "Greška prilikom brisanja lokaliteta", "Greška", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Uspešno obrisan lokalitet", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
                parent.azurirajTabelu();
                this.dispose();
            }
        }
        return;
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LokalitetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LokalitetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LokalitetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LokalitetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LokalitetDialog dialog = new LokalitetDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvajIzmene;
    private javax.swing.JComboBox<JedinicaGazdinstva> jComboBoxJG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDatumDoznakeError;
    private javax.swing.JLabel jLabelDoznakaError;
    private javax.swing.JLabel jLabelJGError;
    private javax.swing.JLabel jLabelOOError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDatumDoznake;
    private javax.swing.JTextField jTextFieldDoznaka;
    private javax.swing.JTextField jTextFieldOdsekOdeljenje;
    // End of variables declaration//GEN-END:variables

    private void inicijalizacija() {
        for (JedinicaGazdinstva jg : JedinicaGazdinstva.values()) {
            jComboBoxJG.addItem(jg);
        }
        jComboBoxJG.setSelectedItem(null);
        jButtonSacuvajIzmene.setVisible(false);
        jButtonIzmeni.setVisible(false);
        jButtonObrisi.setVisible(false);
        java.util.Date datum = new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        String datumString = format.format(datum);
        jTextFieldDatumDoznake.setText(datumString);
        jTextFieldDatumDoznake.setEnabled(false);

        this.setValidationLabels();

    }

    private void inicijalizacija(Lokalitet lokalitet) {
        for (JedinicaGazdinstva jg : JedinicaGazdinstva.values()) {
            jComboBoxJG.addItem(jg);
        }
        jComboBoxJG.setSelectedItem(lokalitet.getJedinicaGazdinstva().toString());
        jComboBoxJG.setEnabled(false);
        jButtonKreiraj.setVisible(false);
        jButtonSacuvajIzmene.setEnabled(false);
        jTextFieldOdsekOdeljenje.setText(lokalitet.getOdsekOdeljenje());
        jTextFieldDoznaka.setText(lokalitet.getDoznaka() + "");
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        try {
            jTextFieldDatumDoznake.setText(format.format(lokalitet.getDatumDoznake()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pogresan format datuma", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jTextFieldOdsekOdeljenje.setEnabled(false);
        jTextFieldDatumDoznake.setEnabled(false);
        jTextFieldDoznaka.setEnabled(false);
        jComboBoxJG.setEnabled(false);

        this.setValidationLabels();

    }

    private void setValidationLabels() {
        jLabelJGError.setText("");
        jLabelOOError.setText("");
        jLabelDoznakaError.setText("");
        jLabelDatumDoznakeError.setText("");
    }
}
