/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import test.AppStyles;
import test.HistogramExample;
import test.StackedDiagram;

/**
 *
 * @author Andrej
 */
public class StatistikaDialog extends javax.swing.JDialog {

    /**
     * Creates new form StatistikaDialog
     */
    private static List<Integer> vreme = new ArrayList<>();
    private static List<Double> vrednosti = new ArrayList<>();
    private static List<String> mesta = new ArrayList<>();
    private static boolean isGodina;

    public StatistikaDialog(java.awt.Frame parent, boolean modal, ArrayList<Integer> vreme, boolean isGodina, ArrayList<Double> vrednosti) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.vreme = vreme;
        this.vrednosti = vrednosti;
        this.isGodina = isGodina;
        HistogramExample.kreirajGrafikon(jPanelGraph, vreme, isGodina, vrednosti);
        ChartPanel chartPanel = (ChartPanel) jPanelGraph.getComponent(0);  // Pretpostavljamo da je grafikon prvi komponent u jPanelGraph
        JFreeChart chart = chartPanel.getChart();  // Dobijanje JFreeChart objekta iz ChartPanel-a

        // Postavljanje stila na grafikon
        AppStyles.setChartStyles(chart);  // Postavljanje stila
    }

    public StatistikaDialog(java.awt.Frame parent, boolean modal, List<Integer> vreme, boolean isGodina, List<String> mesta, List<Double> vrednosti) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.vreme = vreme;
        this.vrednosti = vrednosti;
        this.isGodina = isGodina;
        this.mesta = mesta;
        StackedDiagram.createStackedBarChart(jPanelGraph, mesta, vreme, isGodina, vrednosti);
        ChartPanel chartPanel = (ChartPanel) jPanelGraph.getComponent(0);  // Pretpostavljamo da je grafikon prvi komponent u jPanelGraph
        JFreeChart chart = chartPanel.getChart();  // Dobijanje JFreeChart objekta iz ChartPanel-a

        // Postavljanje stila na grafikon
        AppStyles.setChartStyles(chart);  // Postavljanje stila

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraph = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelGraph.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelGraphLayout = new javax.swing.GroupLayout(jPanelGraph);
        jPanelGraph.setLayout(jPanelGraphLayout);
        jPanelGraphLayout.setHorizontalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        jPanelGraphLayout.setVerticalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatistikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatistikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatistikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatistikaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StatistikaDialog dialog = new StatistikaDialog(new javax.swing.JFrame(), true, vreme, isGodina, mesta, vrednosti);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelGraph;
    // End of variables declaration//GEN-END:variables
}
