/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import email.Email;
import hashing.Hash;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import model.Menadzer;
import model.MenadzerPrivilegija;
import model.Privilegija;

/**
 *
 * @author Andrej
 */
public class RegistracijaForma extends javax.swing.JFrame {

    /**
     * Creates new form RegistracijaForma
     */
    public RegistracijaForma() {
        initComponents();
        setTitle("Registracija");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(RegistracijaForma.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                new PrijavaForma().setVisible(true);
            }
        });
        inicijalizacija();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextFieldJMBG3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldJMBG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldImePrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldKontakt = new javax.swing.JTextField();
        jButtonRegistracija = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxUloga = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelJmbgError = new javax.swing.JLabel();
        jLabelImePrezimeError = new javax.swing.JLabel();
        jLabelKontaktError = new javax.swing.JLabel();
        jLabelEmailError = new javax.swing.JLabel();

        jLabel4.setText("Email");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Ime i prezime");

        jLabel3.setText("Email");

        jLabel5.setText("Kontakt");

        jButtonRegistracija.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRegistracija.setText("Registruj se");
        jButtonRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistracijaActionPerformed(evt);
            }
        });

        jLabel6.setText("Uloga");

        jLabel1.setText("JMBG");

        jLabelJmbgError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelJmbgError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelJmbgError.setText("jLabel7");

        jLabelImePrezimeError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelImePrezimeError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelImePrezimeError.setText("jLabel7");

        jLabelKontaktError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelKontaktError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelKontaktError.setText("jLabel7");

        jLabelEmailError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelEmailError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelEmailError.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistracija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUloga, javax.swing.GroupLayout.Alignment.TRAILING, 0, 204, Short.MAX_VALUE)
                            .addComponent(jLabelEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKontaktError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldKontakt, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldJMBG)
                            .addComponent(jTextFieldImePrezime)
                            .addComponent(jLabelJmbgError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelImePrezimeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelJmbgError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(jLabelImePrezimeError)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKontaktError)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonRegistracija)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistracijaActionPerformed
        if (jTextFieldJMBG.getText().isEmpty() 
                || !jTextFieldJMBG.getText().matches("^[1-9]\\d{12}$")
                || jTextFieldImePrezime.getText().isEmpty() 
                || jTextFieldEmail.getText().isEmpty()
                || !jTextFieldEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")
                || jTextFieldKontakt.getText().isEmpty()) {
            jLabelJmbgError.setText(jTextFieldJMBG.getText().isEmpty() ? "Unesite JMBG" : !jTextFieldJMBG.getText().matches("^[1-9]\\d{12}$") ? "Pogrešan format JMBG-a":"");
            jLabelImePrezimeError.setText(jTextFieldImePrezime.getText().isEmpty() ? "Unesite ime i prezime" : "");
            jLabelEmailError.setText(jTextFieldEmail.getText().isEmpty() ? "Unesite email" : !jTextFieldEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$") ? "Pogrešan format email-a":"");
            jLabelKontaktError.setText(jTextFieldKontakt.getText().isEmpty() ? "Unesite kontakt":"");
            return;
        }
        String jmbg = jTextFieldJMBG.getText();
        String imePrezime = jTextFieldImePrezime.getText();
        String email = jTextFieldEmail.getText();
        String kontakt = jTextFieldKontakt.getText();
        String kriptovana = "";

        Random random = new Random();
        int kod = 10000 + random.nextInt(90000);
        try {
            Email.autentifikacija(email, String.valueOf(kod));
        } catch (MessagingException ex) {
            System.out.println("Greska u slanju koda za autentifikaciju");
            return;
        }

        try {
            kriptovana = Hash.kriptuj(String.valueOf(kod));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(RegistracijaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        Menadzer menadzer = new Menadzer(jmbg, imePrezime, kontakt, kriptovana, email,true);
        Privilegija privilegija = (Privilegija)jComboBoxUloga.getSelectedItem();
        java.util.Date datumSticanja = new java.util.Date();
        MenadzerPrivilegija mp = new MenadzerPrivilegija(menadzer,privilegija,datumSticanja);
        boolean uspesno = Controller.getInstance().kreirajMenadzer(menadzer) && Controller.getInstance().kreirajMenadzerPrivilegija(mp);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Dobili ste jednokratnu lozinku na mail "+email, "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom registracije na sistem", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonRegistracijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistracijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistracijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistracijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistracijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistracijaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistracija;
    private javax.swing.JComboBox<Privilegija> jComboBoxUloga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmailError;
    private javax.swing.JLabel jLabelImePrezimeError;
    private javax.swing.JLabel jLabelJmbgError;
    private javax.swing.JLabel jLabelKontaktError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldImePrezime;
    private javax.swing.JTextField jTextFieldJMBG;
    private javax.swing.JTextField jTextFieldJMBG3;
    private javax.swing.JTextField jTextFieldKontakt;
    // End of variables declaration//GEN-END:variables

    private void inicijalizacija() {
        jLabelJmbgError.setText("");
        jLabelImePrezimeError.setText("");
        jLabelKontaktError.setText("");
        jLabelEmailError.setText("");
        popuniComboBox();
    }

    private void popuniComboBox() {
        List<Privilegija> privilegije = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuPrivilegija(privilegije);
        if(!uspesno){
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja privilegija","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }
        for(Privilegija p: privilegije){
            jComboBoxUloga.addItem(p);
        }
    }
}
